In [1]:
from bs4 import BeautifulSoup

In [2]:
with open("beautifulsoup_practice.html","r") as f:
    html=f.read()
    print(html)

<!DOCTYPE html>
<html>

<head>
    <title>BeautifulSoup Practice Website</title>
</head>

<body>

    <h1 id="main-title">LJU Student Portal</h1>

    <div class="student" data-id="101">

        <h2 class="name">Dhruv Patel</h2>

        <p class="department">Computer Engineering</p>

        <p class="email">
            Email:
            <span>dhruv@gmail.com</span>
        </p>

        <a href="https://linkedin.com/dhruv">
            LinkedIn Profile
        </a>

        <img src="dhruv.jpg" alt="Dhruv Image">

    </div>

    <div class="student" data-id="102">

        <h2 class="name">Riya Shah</h2>

        <p class="department">IT Engineering</p>

        <p class="email">
            Email:
            <span>riya@gmail.com</span>
        </p>

        <a href="https://linkedin.com/riya">
            LinkedIn Profile
        </a>

        <img src="riya.jpg" alt="Riya Image">

    </div>

    <div class="student" data-id="103">

        <h2 class="name">Amit Joshi</h2>

        <p class="department">AI & DS</p>

        <p class="email">
            Email:
            <span>amit@gmail.com</span>
        </p>

        <a href="https://linkedin.com/amit">
            LinkedIn Profile
        </a>

        <img src="amit.jpg" alt="Amit Image">

    </div>

    <hr>

    <h2>Student Marks Table</h2>

    <table border="1" id="marks-table">

        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Python</th>
            <th>Django</th>
        </tr>

        <tr>
            <td>101</td>
            <td>Dhruv</td>
            <td>95</td>
            <td>90</td>
        </tr>

        <tr>
            <td>102</td>
            <td>Riya</td>
            <td>88</td>
            <td>91</td>
        </tr>

        <tr>
            <td>103</td>
            <td>Amit</td>
            <td>92</td>
            <td>85</td>
        </tr>

    </table>

</body>
</html>

In [3]:
soup=BeautifulSoup(html,"html.parser")

In [4]:
z=soup.find("h1")

In [5]:
z

In [7]:
soup.find("h2",{"class":"name"}).text.strip()

'Dhruv Patel'

In [8]:
title=soup.find("h1").text

In [9]:
title

'LJU Student Portal'

In [10]:
name=soup.find("h2",{"class":"name"}).text

In [11]:
name

'Dhruv Patel'

In [12]:
dep=soup.find("p",{"class":"department"}).text

In [13]:
dep

'Computer Engineering'

In [14]:
email=soup.find("p",{"class":"email"}).text

In [35]:
emaill=email.split("\n")[2].strip()

In [92]:
ename=emaill.split("@")
ename

['dhruv', 'gmail.com']

In [36]:
social=soup.find("a").text

In [37]:
sociall=social.split("\n")[1].strip()

In [38]:
import pandas as psd

In [56]:
data={"title":[title],"name":[name],"email":[emaill],"dep":[dep],"SOCIAL":[sociall]}

In [57]:
data

{'title': ['LJU Student Portal'],
 'name': ['Dhruv Patel'],
 'email': ['dhruv@gmail.com'],
 'dep': ['Computer Engineering'],
 'SOCIAL': ['LinkedIn Profile']}

In [58]:
df=psd.DataFrame(data)

In [59]:
df

,title,name,email,dep,SOCIAL
0,LJU Student Portal,Dhruv Patel,dhruv@gmail.com,Computer Engineering,LinkedIn Profile

# find_all

In [85]:
l1=soup.find_all("div",{"class":"student"},limit=2)

In [125]:
name=[]
email=[]
dept=[]
social=[]
link=[]
ext=[]
img=[]
for i in l1:
    n=i.find("h2").text
    name.append(n)
    e=i.find("span").text.split("@")[0]
    email.append(e)
    x=i.find("span").text[-10:]
    ext.append(x)
    d=i.find("p").text
    dept.append(d)
    s=i.find("a").text.strip()
    social.append(s)
    l=i.find("a")
    link.append(l["href"])
    im=i.find("img")
    img.append(im["src"])

In [126]:
data={"name":name,"email":email,"ext":ext
      ,"dep":dept,"SOCIAL":social,"link":link,"img":img}

In [127]:
data

{'name': ['Dhruv Patel', 'Riya Shah'],
 'email': ['dhruv', 'riya'],
 'ext': ['@gmail.com', '@gmail.com'],
 'dep': ['Computer Engineering', 'IT Engineering'],
 'SOCIAL': ['LinkedIn Profile', 'LinkedIn Profile'],
 'link': ['https://linkedin.com/dhruv', 'https://linkedin.com/riya'],
 'img': ['dhruv.jpg', 'riya.jpg']}

In [128]:
df=psd.DataFrame(data)

In [129]:
df

,name,email,ext,dep,SOCIAL,link,img
0,Dhruv Patel,dhruv,@gmail.com,Computer Engineering,LinkedIn Profile,https://linkedin.com/dhruv,dhruv.jpg
1,Riya Shah,riya,@gmail.com,IT Engineering,LinkedIn Profile,https://linkedin.com/riya,riya.jpg